config/routes.rb
Bookmate::Application.routes.draw do

  match "like" => "likes#like", :as => "like"

  resources :scrapers

  resources :sessions

  resources :users

  resources :passages

  resources :stickers do
    get 'random_quotes', :on => :collection
  end

  get 'register' => 'users#new', :as => :register
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :tags

  root :to => "quotes#index"
  resources :urls

  resources :covers

  resources :quotes

  resources :authors

  resources :books

end

app/models/url.rb
class Url < ActiveRecord::Base
  belongs_to :quote

  validates :link, :presence => true
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @urls }
    end
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
    @url = Url.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @url }
    end
  end

  # GET /urls/new
  # GET /urls/new.json
  def new
    @url = Url.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @url }
    end
  end

  # GET /urls/1/edit
  def edit
    @url = Url.find(params[:id])
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(params[:url])

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render json: @url, status: :created, location: @url }
      else
        format.html { render action: "new" }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /urls/1
  # PUT /urls/1.json
  def update
    @url = Url.find(params[:id])

    respond_to do |format|
      if @url.update_attributes(params[:url])
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url = Url.find(params[:id])
    @url.destroy

    respond_to do |format|
      format.html { redirect_to urls_url }
      format.json { head :ok }
    end
  end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :quote %><br />
    <%= f.text_field :quote %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing url</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<h1>Listing urls</h1>

<table>
  <tr>
    <th>Link</th>
    <th>Quote</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @urls.each do |url| %>
  <tr>
    <td><%= url.link %></td>
    <td><%= url.quote %></td>
    <td><%= link_to 'Show', url %></td>
    <td><%= link_to 'Edit', edit_url_path(url) %></td>
    <td><%= link_to 'Destroy', url, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<h1>New url</h1>

<%= render 'form' %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Link:</b>
  <%= @url.link %>
</p>

<p>
  <b>Quote:</b>
  <%= @url.quote %>
</p>


<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>