config/routes.rb
Bookmate::Application.routes.draw do

  match "like" => "likes#like", :as => "like"

  resources :scrapers

  resources :sessions

  resources :users

  resources :passages

  resources :stickers do
    get 'random_quotes', :on => :collection
  end

  get 'register' => 'users#new', :as => :register
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :tags

  root :to => "quotes#index"
  resources :urls

  resources :covers

  resources :quotes

  resources :authors

  resources :books

end

app/views/shared/_about.html.haml
#about
  %p
    = "Это сайтик " 
    = link_to "Лилички", "http://quotemate.heroku.com/users/lili4ka"

  %p
    ="Cюда можно добавлять" 
    =link_to "что угодно", quotes_path
    ="из любого места"
  %p
    ="Вы можете тоже попробовать. Для этого нужно"
    =link_to "записаться", :register
    ="и"
    =link_to "зайти", :login
  =render "/shared/privacy"

app/views/shared/_author.html.haml
- if quote.user
  .author
    ="добавлено"
    =link_to quote.user.username, quote.user

app/views/shared/_footer.html.haml
#separator
.left
  =render "/shared/privacy"
.right
  = "Made with love by"
  = link_to "Lili Gray", "http://vk.com/i00000000002"

app/views/shared/_header.html.haml
- if logged_in?
  = render '/shared/user_bar'
- else
  = render '/shared/signin_or_signup_bar'
.top-bar
  =link_to "Мысли", quotes_path
  =link_to "Источники", books_path
  =link_to "Гадать", random_quotes_stickers_path
  =link_to "Дзэн", tags_path
  =link_to "About", "#about", {:class => "fancy-link"}

%div{:style=>"display:none;"}
  =render "shared/about"

app/views/shared/_metrika.html.haml
- content_for :js do
  :javascript
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter18279979 = new Ya.Metrika({id:18279979,
                      clickmap:true,
                      trackLinks:true,
                      accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");

app/views/shared/_privacy.html.haml
.nano
  ="Все, что содержит этот сайтик, можно использовать в целях зарабатывания денег, очистки кармы, пропаганды гомосексуализма и нетолерантности и вообще в любых других целях, хотела бы я посмотреть, как у вас это получится ихихих."

app/views/shared/_signin_or_signup_bar.html.haml
#signin_or_signup_bar
  .top
    .mini-form#login
      = form_for User.new, :url => :sessions, :method => :post, :html => {:remote => true, :data => {:type => :script}} do |f|
        .field.text
          = f.label :email
          = f.text_field :email
        .field.text
          = f.label :password, f.object.class.human_attribute_name(:password), :for => 'login_password'
          = f.password_field :password, :id => 'login_password'
        .actions
          = f.submit t(".sign_in")

    .mini-form#registration
      = form_for User.new, :html => { :remote => true, :'data-type' => :script } do |f|
        .field.text
          = f.label :username
          = f.text_field :username
        .field.text
          = f.label :email
          = f.text_field :email
        .field.text
          = f.label :password
          = f.password_field :password
        .field.text
          = f.label :password_confirmation
          = f.password_field :password_confirmation
        .actions
          = f.submit t(".reg"), :disable_with => t(".reg_in_progress")

  .bottom
    .btn-group
      = link_to "Зайти", :login, :data => { :link => 'login'}
      = link_to "Записаться", :register, :data => { :link => 'registration'}

- content_for :js do
  :javascript
    $(function() {
      var scope = $('#signin_or_signup_bar'),
          effect = 'blind',
          buttons = scope.find('.bottom .btn'),
          miniForms = scope.find('.top').children('.mini-form');

      buttons.on('click', function(e) {
        e.preventDefault();

        var button = $(this),
            showFormId = $(this).data('link'),
            visibleForm = miniForms.filter(':visible');

        var showForm = function() {
          buttons.not($(this)).removeClass('active');
          button.addClass('active');
          miniForms.filter('#'+showFormId).show(effect, {}, 300, function() {
            $(this).find('form input:text').first().focus();
          });
        };

        if (visibleForm.attr('id') == showFormId){
          visibleForm.hide(effect, {}, 300);
          button.removeClass('active');
          return ;
        }

        if (visibleForm.length){
          visibleForm.hide(effect, {}, 300, function() { showForm(); });
        } else {
          showForm();
        }
      });

app/views/shared/_user_bar.html.haml
.user-bar
  = link_to current_user.username, current_user
  =", "
  = Quote.short.first(:order => "RANDOM()").text.downcase
  