config/routes.rb
Bookmate::Application.routes.draw do

  match "like" => "likes#like", :as => "like"

  resources :scrapers

  resources :sessions

  resources :users

  resources :passages

  resources :stickers do
    get 'random_quotes', :on => :collection
  end

  get 'register' => 'users#new', :as => :register
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :tags

  root :to => "quotes#index"
  resources :urls

  resources :covers

  resources :quotes

  resources :authors

  resources :books

end

app/models/passage.rb
class Passage < ActiveRecord::Base

  belongs_to :book

  def book_title
    book.try(:title)
  end

  def book_title=(title)
    self.book = Book.find_or_create_by_title(title) if title.present?
  end

end

app/controllers/passages_controller.rb
class PassagesController < InheritedResources::Base
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/views/passages/_form.html.haml
= form_for(@passage) do |f|
  - if @passage.errors.any?
    #error_explanation
    %h2
      = pluralize(@passage.errors.count, "error")
      = "prohibited this passage from being saved:"

    %ul
      - @passage.errors.full_messages.each do |msg|
        %li
          = msg
  .field
    = f.label "Что пишем"
    %br
    = f.text_field :text, :size => 100
  %br
  =link_to "Может, это из книги?", "#",{:class => "notice", :id => "book-notice"}
  
  .field-hidden{:style => "display:none;", :id => "book-field-hidden"}
    = f.label "Источник (фильм, книга, etc  — название, например)"
    %br
    = f.text_field :book_title, data: {autocomplete_source: Book.order(:title).map(&:title)}
  .actions
    = f.submit "В молескин", {:class => "submit"}

app/views/passages/edit.html.erb
<h1>Editing passage</h1>

<%= render 'form' %>

<%= link_to 'Show', @passage %> |
<%= link_to 'Back', passages_path %>

app/views/passages/index.html.erb
<h1>Listing passages</h1>

<table>
  <tr>
    <th>Text</th>
    <th>Book</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% Passage.order('created_at desc').each do |passage| %>
  <tr>
    <td><%= passage.text %></td>
    <td><%= passage.book_id %></td>
    <td><%= link_to 'Show', passage %></td>
    <td><%= link_to 'Edit', edit_passage_path(passage) %></td>
    <td><%= link_to 'Destroy', passage, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Passage', new_passage_path %>

app/views/passages/new.html.erb
<h1>New passage</h1>

<%= render 'form' %>

<%= link_to 'Back', passages_path %>

app/views/passages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @passage.text %>
</p>

<p>
  <b>Book:</b>
  <%= @passage.book_id %>
</p>


<%= link_to 'Edit', edit_passage_path(@passage) %> |
<%= link_to 'Back', passages_path %>